export const inputLanguageMap = {
  English: "English",
  Cantonese: "Chinese (Cantonese, Traditional)",
  Hindi: "Hindi (India)",
  Japanese: "Japanese (Japan)",
  Korean: "Korean (Korea)",
  Mandarin: "Chinese (Mandarin, Simplified)",
  Portuguese: "Portuguese (Portugal)",
  Spanish: "Spanish (United States)",
  Tagalog: "Filipino (Philippines)",
  Thai: "Thai (Thailand)",
  Turkish: "Turkish (Türkiye)",
  Vietnamese: "Vietnamese (Vietnam)",
};

export const outputLanguageMap = {
  Arabic: "Arabic",
  Bengali: "Bengali (India)",
  Burmese: "Burmese (Myanmar)",
  Cantonese: "Chinese (Cantonese, Traditional)",
  English: "English",
  Farsi: "Persian (Iran)",
  French: "French (France)",
  German: "German (Germany)",
  Gujarati: "Gujarati (India)",
  Hebrew: "Hebrew (Israel)",
  Hindi: "Hindi (India)",
  Indonesian: "Indonesian (Indonesia)",
  Italian: "Italian (Italy)",
  Japanese: "Japanese (Japan)",
  Korean: "Korean (Korea)",
  Lao: "Lao (Laos)",
  Malay: "Malay (Malaysia)",
  Malayalam: "Malayalam (India)",
  Mandarin: "Chinese (Mandarin, Simplified)",
  Nepali: "Nepali (Nepal)",
  Polish: "Polish (Poland)",
  Portuguese: "Portuguese (Portugal)",
  Russian: "Russian (Russia)",
  Spanish: "Spanish (United States)",
  Tagalog: "Filipino (Philippines)",
  Tamil: "Tamil (India)",
  Telugu: "Telugu (India)",
  Thai: "Thai (Thailand)",
  Ukrainian: "Ukrainian (Ukraine)",
  Urdu: "Urdu (Pakistan)",
  Vietnamese: "Vietnamese (Vietnam)",
};

export type InputLanguageKey = keyof typeof inputLanguageMap;
export type OutputLanguageKey = keyof typeof outputLanguageMap;
